### PR TITLE
Ensure tree directories are emitted with hashes

### LINKED ISSUE #1910: Bazel crashes on ActionCache replies with directory trees
Since [PR-1870](https://github.com/buildfarm/buildfarm/pull/1870), our Bazel client (7.2.1 and 7.4.0rc4 and 7.4.0) crash with the following stacktrace:

```
(20:01:49) FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData0{actionLookupKey=ConfiguredTargetKey{label=//<REDACTED>, config=BuildConfigurationKey[bfedefdc22aebf3cda9247404ac1b7b3bff251e71d31d0b7f5766285194d085b]}, actionIndex=0}' (requested by nodes 'File:[[<execution_root>]bazel-out/k8-fastbuild/bin]<REDACTED>/path/to/dir')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
	at com.google.devtools.build.lib.remote.RemoteExecutionService.parseDirectory(RemoteExecutionService.java:1017)
	at com.google.devtools.build.lib.remote.RemoteExecutionService.parseActionResultMetadata(RemoteExecutionService.java:1058)
	at com.google.devtools.build.lib.remote.RemoteExecutionService.downloadOutputs(RemoteExecutionService.java:1137)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.downloadAndFinalizeSpawnResult(RemoteSpawnRunner.java:454)
	at com.google.devtools.build.lib.remote.RemoteSpawnRunner.exec(RemoteSpawnRunner.java:224)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:158)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:118)
	at com.google.devtools.build.lib.exec.SpawnStrategyResolver.exec(SpawnStrategyResolver.java:45)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:261)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:1159)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1076)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:165)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:94)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:573)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:859)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:333)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:171)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
```

### PR DESCRIPTION
**Pull request by werkt**
Adding multiple digest functions created many short-lived DigestUtils where efforts to reduce the number of instances of the empty digest for each digest function pushed the empty into the hash function enums. Failing to return the empty() digest, in favor of the digest default instance, resulted in incorrect presentation of directories in REAPI Trees, used in output directory execution results. We now test that a) the digest util always results in a compute()d cached empty() reference, and b) that Tree Directories will have digest references with hashes for all, including non-empty, directories present in the children list.
Fixes #1910

### CODE REVIEW

File: src/main/java/build/buildfarm/common/DigestPath.java [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+// limitations under the License.
+
+package build.buildfarm.common;
+
+import build.buildfarm.v1test.Digest;
+import java.nio.file.Path;
+import lombok.Data;
+
+@Data
+public final class DigestPath {
```
Comment (jasonschroeder-sfdc) [inline src/main/java/build/buildfarm/common/DigestPath.java:22]: How about a Java 17 "Record"? https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Record.html

File: src/main/java/build/buildfarm/common/function/IOConsumer.java [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+// distributed under the License is distributed on an "AS IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+package build.buildfarm.common.function;
+
+import java.io.IOException;
+
+@FunctionalInterface
```
Comment (jasonschroeder-sfdc) [inline src/main/java/build/buildfarm/common/function/IOConsumer.java:19]: Javadoc the purpose? Looks like a Supplier or similar

File: src/main/java/build/buildfarm/common/DigestPath.java (hunk 1 above)
Comment (werkt) [reply src/main/java/build/buildfarm/common/DigestPath.java:22]: Neat. Done. We should switch a bunch of things over to this.

**Review by jasonschroeder-sfdc — APPROVED** [review]
Thank you for fixing this!
